Repository PennyLaneAI/pennylane-qiskit, pull requests merged in 2020-04, with the labels that each got.

#79 Replace index page with overview page
  README.rst
  doc/code.rst
  doc/devices/overview.rst
  doc/index.rst
  doc/xanadu_theme/globaltoc.html
Labels: documentation, review-ready

#81 Qiskit v0.18 updates
  pennylane_qiskit/qiskit_device.py
  tests/test_converter.py
Labels: merge-ready

#80 QiskitDevice.probabilities() changed to QiskitDevice.probability() to…
  CHANGELOG.md
  pennylane_qiskit/qiskit_device.py
  tests/test_apply.py
  tests/test_qiskit_device.py
Labels: merge-ready

#82 IBMQ probs test
  CHANGELOG.md
  tests/test_ibmq.py
Labels: merge-ready

#83 Porting to QubitDevice
  pennylane_qiskit/qiskit_device.py
  tests/test_apply.py
  tests/test_expval.py
  tests/test_ibmq.py
  tests/test_integration.py
  tests/test_inverses.py
  tests/test_qiskit_device.py
  tests/test_sample.py
  tests/test_var.py
Labels: review-ready
